apiVersion: batch/v1
kind: CronJob
metadata:
  name: sailrsv
  namespace: myscal
spec:
  schedule: "45 16 * * *"  
  concurrencyPolicy: "Forbid" 
  startingDeadlineSeconds: 200 
  suspend: false            
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 1     
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            run: sailrsv
        spec:
          containers:
          - name: sailrsv
            image: 172.30.118.67:5000/myscal/sailrsv
          restartPolicy: Never
